# Generated by Django 4.2.6 on 2023-10-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contacty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacty',
            name='email',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contacty',
            name='name',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='contacty',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
