# Generated by Django 4.2.6 on 2023-10-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
